name: diagnosis_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # UI
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  carousel_slider_plus: ^7.0.1
  colornames: ^0.1.0
  dotted_border: ^3.1.0
  fl_chart: ^1.1.1

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.7.0
  dotted_border: ^3.1.0
  file_picker: ^8.3.7
  fl_chart: ^0.66.2
  flutter_bloc: ^8.1.6

  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  gap: ^3.0.1
  smooth_page_indicator: ^1.2.0+3

  # State Management & DI
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  injectable: ^2.4.4


  # Network & Data
  dio: ^5.7.0
  dartz: ^0.10.1
  retrofit: ^4.5.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Utils
  device_preview: ^1.2.0
  file_picker: ^10.3.7
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  jwt_decoder: ^2.0.1


  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0
  jwt_decoder: ^2.0.1
  retrofit: ^4.9.2
  freezed_annotation: ^2.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  retrofit_generator: ^9.1.5
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/SplashScreen.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/
    - assets/image_SVG/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

flutter_intl:
  enabled: true
